version: '3.7'
services:
  postgres:
    image: postgres:11.5-alpine
    container_name: postgresproduction
    env_file: .env
    networks: 
      - webnet
    ports:
      - "4242:5432"
  app:
    build: .
    command: npm start
    restart: always
    env_file: .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks: 
      - webnet
networks: 
  webnet: